### ISSUE TITLE
关于您的configs解释？

### ISSUE THREAD

**Issue by Peterisfar** [ming71/mmdetection-annotated#1]
1、configs中batchsize是在哪里说明的？
2、config中的img_scale 是什么意思？
3、您在本地训练是训练的什么数据，用几个gpu?如果单gpu,你的lr是多少？能提供一下实际的本地训练配置文件吗？谢谢

**Comment by saicheshoulbl** [comment]
1. imgs_per_gpu=2,                # 每个gpu计算的图像数量
    workers_per_gpu=2,             # 每个gpu分配的线程数
        batch_size = num_gpus * imgs_per_gpu
        num_workers = num_gpus * workers_per_gpu

2.img_scale 是输入图像尺寸的意思

3.lr和GPU个数没关系。你想问的应该是lr的优化策略,可以看里面的lr_config

**Comment by ming71** [comment]
> 1. imgs_per_gpu=2,                # 每个gpu计算的图像数量
>    workers_per_gpu=2,             # 每个gpu分配的线程数
>    batch_size = num_gpus * imgs_per_gpu
>    num_workers = num_gpus * workers_per_gpu
> 
> 2.img_scale 是输入图像尺寸的意思
> 
> 3.lr和GPU个数没关系。你想问的应该是lr的优化策略,可以看里面的lr_config



> 1、configs中batchsize是在哪里说明的？
> 2、config中的img_scale 是什么意思？
> 3、您在本地训练是训练的什么数据，用几个gpu?如果单gpu,你的lr是多少？能提供一下实际的本地训练配置文件吗？谢谢

楼上的这位说的很明白了。<br>
不过有个瑕疵，作者的lr设置是8块GPU情况下调出来的，你应该根据自己的GPU数据来进行重新设置。比如你一块GPU，就应该设置为原来的1/8。<br>
这一点我自己在COCO上试验过了，确实如此。
