### ISSUE TITLE
模型可视化

### ISSUE THREAD

**Issue by shuxp** [ming71/mmdetection-annotated#4]
你好，你的模型可视化用的什么工具？能否分享下？谢谢～

**Comment by ming71** [comment]
Netron

**Comment by shuxp** [comment]
> Netron

我试了，但是对于检测任务都只会出现下面独立模块，不知道你那边存储模型的时候是否做了特殊处理呢？

![image](https://user-images.githubusercontent.com/7609868/59826158-4a10af00-9368-11e9-8525-485390cbc30b.png)

**Comment by ming71** [comment]
Netron只能识别继承自nn.Module的特定类。你这个结果已经比较详细了，还有什么问题吗？或者说你想要的怎样的模型？

**Comment by shuxp** [comment]
我的模型是用https://github.com/jwyang/faster-rcnn.pytorch 代码训练出来的，自己改了些东西，用Netron打开就是上面那样，我看了下Netron的源码，可惜electron不熟。。

你能帮忙提点意见嘛

**Comment by ming71** [comment]
你想要什么样的结构啊...我看你可视化的已经很详细了啊

**Comment by shuxp** [comment]
看不到箭头，不知道数据流流向以及各个地方的输出维度。。

**Comment by nuist-xinyu** [comment]
作者你好，关注你这个github很久了，能不能加你一个联系方式

**Comment by ming71** [comment]
> 作者你好，关注你这个github很久了，能不能加你一个联系方式

邮箱mq_chaser@126.com，可以邮件联系

**Comment by ming71** [comment]
> 看不到箭头，不知道数据流流向以及各个地方的输出维度。。

额，如果netron不行的话，还有一个更好用的工具keras的自带可视化模块。找一个相同网络的keras实现版本，用自带可视化模块输出模型结构就行。希望能帮到你==
