### ISSUE TITLE
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xytjcxy** [ming71/mmdetection-annotated#6]
您好，我用的是cuda10.0，因此它这里报错，无libcudart.so.9.0，请问如何解决呢？

**Comment by xytjcxy** [comment]
运行complie.sh文件

**Comment by zyccccc** [comment]
你好，我和你报的一样的错误，可以详细点吗，是什么compile.sh文件，我没有这个文件，谢谢！

**Comment by xytjcxy** [comment]
> 你好，我和你报的一样的错误，可以详细点吗，是什么compile.sh文件，我没有这个文件，谢谢！

他上一个版本是有complie.sh文件，这一个版本可能就没有了。无libcudart.so.9.0是少了一个可执行文件，这个可执行文件需要执行compile.sh编译获取。如果没有complie.sh，我也没办法了
